FROM graphql_frontend
MAINTAINER Thomas Rampelberg <thomasr@vapor.io>

# Run the dependencies as a single layer
COPY testing-requirements.txt /graphql_frontend/testing-requirements.txt
RUN apk add --update alpine-sdk && \
  pip install -r /graphql_frontend/testing-requirements.txt

CMD /bin/sh
