version: "2"
services:
  graphql_frontend:
    container_name: graphql_frontend
    build:
      context: .
      dockerfile: Dockerfile.x64
    ports:
      - "5001:5000"
    volumes:
     - .:/graphql_frontend
