#
# prometheus.yml
#
# A simple Prometheus configuration for connecting a Prometheus
# instance with the Prometheus exporter that comes as part of
# synse-graphql. For an example of how to use this, follow the
# Synse monitoring tutorial at https://github.com/vapor-ware/synse
#
scrape_configs:
  - job_name: 'synse'

    static_configs:
      - targets: ['synse-graphql:5050']
