version: "3"
services:
  graphql:
    image: vaporio/synse-graphql:dev-${GIT_VER}
    build:
      dockerfile: dockerfile/dev.dockerfile
    volumes:
      - ..:/code
    command: bin/sleep.sh
    ports:
      - 5001:5001

  synse-server:
    container_name: synse-server
    image: vaporio/synse-server:2.0.0
    restart: always
    command: enable-emulator
    ports:
      - 5000:5000
    environment:
      - VAPOR_DEBUG=true
