version: "3"
services:
  graphql:
    image: vaporio/synse-graphql:dev-${GIT_VER}
    build:
      dockerfile: dockerfile/dev.dockerfile
    volumes:
      - ..:/code
    command: bin/sleep.sh
    ports:
      - 5050:5050

  synse-server:
    container_name: synse-server
    image: vaporio/synse-server:2.1.0
    restart: always
    ports:
      - 5000:5000
    environment:
      SYNSE_LOGGING: debug
      SYNSE_PLUGIN_TCP: emulator-plugin:5001
    links:
      - emulator-plugin

  emulator-plugin:
    container_name: emulator-plugin
    image: vaporio/emulator-plugin
    ports:
      - 5001:5001
    volumes:
      - ../config/emulator/tcp:/tmp/config/
      - ../config/emulator/devices:/tmp/devices/
    environment:
      PLUGIN_CONFIG: /tmp/config
      PLUGIN_DEVICE_PATH: /tmp/devices

  synse-server-2:
    container_name: synse-server-2
    image: vaporio/synse-server:2.1.0
    restart: always
    ports:
      - 5003:5000
    environment:
      SYNSE_LOGGING: debug
      SYNSE_PLUGIN_TCP: test-plugin:5002
    links:
      - test-plugin

  test-plugin:
    container_name: test-plugin
    image: vaporio/test-plugin
    expose:
      - 5002
