version: "3"
services:
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server
    restart: always
    command: enable-emulator
    ports:
      - 5000:5000
    environment:
      SYNSE_LOGGING: debug

  synse-server-2:
    container_name: synse-server-2
    image: vaporio/synse-server
    restart: always
    command: enable-emulator
    ports:
      - 5003:5000
    environment:
      SYNSE_LOGGING: debug
