version: "3"
services:
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server:2.0.0
    restart: always
    command: enable-emulator
    ports:
      - 5000:5000
    environment:
      - SYNSE_LOGGING=debug
